name: Main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Test
      run: poetry run python -m pytest ./tests --cov=pythoncz --tb=native
    - if: ${{ github.event_name == 'pull_request' }}
      name: Build without fetching GitHub Issues
      run: |
        export DISABLE_GITHUB_ISSUES_FETCH=true
        poetry run python runserver.py freeze
    - if: ${{ github.event_name != 'pull_request' }}
      name: Build with fetching GitHub Issues
      run: poetry run python runserver.py freeze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Deploy
      run: poetry run python runserver.py deploy --no-freeze --push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
